server:
  port: 29001

Spring:
  application:
    name: log-consumer-service

eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:27001/eureka
  instance:
    instance-id: logConsumer

#hystrix的超时时间
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 30000
#ribbon的超时时间
ribbon:
  ReadTimeout: 30000
  ConnectTimeout: 30000
