server:
  port: 29001

Spring:
  application:
    name: logConsumer

eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:27001/eureka
  instance:
    instance-id: logConsumer

