server:
  port: 25001

Spring:
  application:
    name: log-index-database-service
  datasource:
    url: jdbc:mysql://10.177.73.196/log
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:27001/eureka
  instance:
    instance-id: logIndexDataBase

mybatis-plus:
  type-enums-package: org.fudan.springcloud.status