server:
  port: 28001

Spring:
  application:
    name: log-producer-service

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:27001/eureka
  instance:
    instance-id: logProducer