server:
  port: 28080

Spring:
  application:
    name: webService

eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:27001/eureka

feign:
  client:
    config: # 默认为所有的feign client做配置(注意和上例github-client是同级的)
      default:
        connectTimeout: 5000 # 连接超时时间
        readTimeout: 5000 # 读超时时间设置 ‘
